# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20171127_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='课程概述'),
        ),
        migrations.AlterField(
            model_name='course',
            name='brief',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='课程简介'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.CourseSubCategory', verbose_name='课程类别'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='课程大类'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursechapters', to='repository.Course', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='course_slogan',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='课程口号'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='video_brief_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='课程介绍(视频id用来生成链接)'),
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='course_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.CourseDetail', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursesections', to='repository.CourseChapter', verbose_name='所属章节'),
        ),
        migrations.AlterField(
            model_name='coursesubcategory',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='课程子类'),
        ),
        migrations.AlterField(
            model_name='degreecourse',
            name='brief',
            field=models.TextField(blank=True, null=True, verbose_name='学位课程简介'),
        ),
        migrations.AlterField(
            model_name='degreecourse',
            name='course_img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='degreecourse',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='oftenaskedquestion',
            name='question',
            field=models.CharField(max_length=255, verbose_name='问题标题'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='degree_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.DegreeCourse', verbose_name='学位课程'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
    ]
