# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('repository', '0003_auto_20171128_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rbac_role',
            field=models.ManyToManyField(to='rbac.Role', verbose_name='rbac角色'),
        ),
    ]
