# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_account_rbac_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='rbac_role',
            new_name='roles',
        ),
    ]
