# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20171128_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Account', verbose_name='用户'),
        ),
    ]
