# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20171128_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='money_equivalent_value',
            field=models.IntegerField(blank=True, help_text='折扣券时,此字段不写', null=True, verbose_name='等值货币'),
        ),
    ]
